apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collectl
  namespace: collectl
  labels:
    app: collectl
spec:
  selector:
    matchLabels:
      app: collectl
  template:
    metadata:
      labels:
        app: collectl
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        collectl: "true"
      serviceAccountName: default
      hostPID: true
      hostNetwork: true
      hostIPC: true
      terminationGracePeriodSeconds: 60
      containers:
      - name: collectl
        image: quay.io/acancell-redhat/ocp_collectl_cpu:4.3.20-ubi9
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 800Mi
          limits:
            memory: 1Gi
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - mountPath: /dev/mem
          name: dev-mem
        - mountPath: /var/log/collectl
          name: collectl-logs
        - mountPath: /etc/collectl.conf
          subPath: collectl.conf
          name: collectl-config
      volumes:
      - name: dev-mem
        hostPath:
          path: /dev/mem
          type: CharDevice
      - name: collectl-logs
        hostPath:
          path: /var/log/collectl
          type: DirectoryOrCreate
      - name: collectl-config
        configMap:
          name: collectl-conf